# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build OSLC 3 prototype RIO
      run: mvn -B validate --file rio-oslc3/org.eclipse.lyo.oslc.v3.sample/pom.xml
    - name: Build OSLC 2.0 DEPRECATED RIO (CM, QM, Auto)
      run: mvn -B validate --file rio-oslc4j/org.eclipse.lyo.oslc4j.rio.build/pom.xml
    - name: Build OSLC 2.0 DEPRECATED RIO no. 2 (Core)
      run: mvn -B install --file rio/org.eclipse.lyo.rio.core/pom.xml
    - name: Build OSLC 2.0 DEPRECATED RIO no. 2 (AM)
      run: mvn -B validate --file rio/org.eclipse.lyo.rio.am/pom.xml
    - name: Build OSLC 2.0 DEPRECATED RIO no. 2 (CM)
      run: mvn -B validate --file rio/org.eclipse.lyo.rio.cm/pom.xml
    - name: Build OSLC 2.0 DEPRECATED RIO no. 2 (RM)
      run: mvn -B validate --file rio/org.eclipse.lyo.rio.rm/pom.xml
#     - name: Build OSLC 2.0 DEPRECATED RIO no. 2 (TRS)
#       run: mvn -B install --file rio/org.eclipse.lyo.rio.trs/pom.xml
#     - name: Build OSLC 2.0 DEPRECATED RIO no. 2 (TRS Tests)
#       run: mvn -B validate --file rio/org.eclipse.lyo.rio.trs.tests/pom.xml
